### ISSUE TITLE
Using the current development branch i get an error

### ISSUE THREAD

**Issue by garbast** [FluidTYPO3/schemaker#64]
I'm using the current (2017.08.04) development branch and get the following errors.

╭─sftpx260 /home/www/dev/dev8/.Build/Web ⌚ 8:44:25
╰─➤  /usr/bin/php7.0 ./typo3/cli_dispatch.phpsh extbase schema:generate sf_register                                                         1 ↵
An error occured while trying to generate the XSD schema for "sf_register":
No ViewHelpers found in namespace "sf_register"
Oops, an error occurred: The request has been terminated as the response defined an exit code.

╭─sftpx260 /home/www/dev/dev8/.Build/Web ⌚ 8:43:36
╰─➤  /usr/bin/php7.0 ./typo3/cli_dispatch.phpsh extbase schema:generate --extension-key Evoweb\SfRegister                                                   1 ↵
An error occured while trying to generate the XSD schema for "EvowebSfRegister":
TYPO3 Fatal Error: Extension key "evoweb_sf_register" is NOT loaded!
Oops, an error occurred: The request has been terminated as the response defined an exit code.

Either tries are not working. What am i doing wrong?

**Comment by NamelessCoder** [comment]
If you view the help text for the command, it says that the `extension-key` argument must be in the `Vendor.ExtensionName` format. This is the only format which allows both creating an expected class name *and* detecting a path for expected classes in the extension's folder, so that's the one we must require. Core namespaces are written as `TYPO3.CMS.ExtensionName` e.g. `TYPO3.CMS` is the pseudo vendor name here due to the odd naming TYPO3 uses for system extensions.

I agree this name is less than obvious but it is this way for legacy reasons. The substitute XSD generator, `typo3/fluid-schema-generator`, works solely by PHP namespaces. You may want to try that one instead (since contrary to EXT:schemaker, that generator is capable of documenting combined namespaces and as such will be able to also generate XSD for the `f:` namespace).
